name: cs_monero_flutter_libs_android_x86_64
description: "Android x86_64 bins for cs_monero_flutter_libs"
version: 0.0.1-dev.0
repository: https://github.com/cypherstack/cs_monero
homepage: https://github.com/cypherstack/cs_monero
issue_tracker: https://github.com/cypherstack/cs_monero/issues

environment:
  sdk: ^3.5.3
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.cypherstack.cs_monero_flutter_libs_android_x86_64
        pluginClass: CsMoneroFlutterLibsAndroidX8664Plugin
