name: compat
description: A compat layer for old flutter_libmonero.
version: 1.0.0
repository: https://github.com/cypherstack/cs_monero
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.1
  hive: ^2.2.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
