name: cs_monero_flutter_libs
description: "Binaries required to use cs_monero in a Flutter project"
version: 1.0.0-pre.0
repository: https://github.com/cypherstack/cs_monero
homepage: https://github.com/cypherstack/cs_monero
issue_tracker: https://github.com/cypherstack/cs_monero/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_monero_flutter_libs_platform_interface: 1.0.0-pre
  cs_monero_flutter_libs_android: 1.0.0-pre
  cs_monero_flutter_libs_ios: 1.0.0-pre.0
  cs_monero_flutter_libs_linux: 1.0.0-pre
  cs_monero_flutter_libs_macos: 1.0.0-pre
  cs_monero_flutter_libs_windows: 1.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cs_monero_flutter_libs_android
      ios:
        default_package: cs_monero_flutter_libs_ios
      linux:
        default_package: cs_monero_flutter_libs_linux
      macos:
        default_package: cs_monero_flutter_libs_macos
      windows:
        default_package: cs_monero_flutter_libs_windows
