name: cs_monero_flutter_libs_android
description: Android implementation of cs_monero_flutter_libs
version: 0.0.1-dev.0
repository: https://github.com/cypherstack/cs_monero
homepage: https://github.com/cypherstack/cs_monero
issue_tracker: https://github.com/cypherstack/cs_monero/issues

environment:
  sdk: ^3.5.3
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_monero_flutter_libs_platform_interface: 0.0.1-dev.1
  cs_monero_flutter_libs_android_x86_64: 0.0.1-dev.0
  cs_monero_flutter_libs_android_armeabi_v7a: 0.0.1-dev.0
  cs_monero_flutter_libs_android_arm64_v8a: 0.0.1-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: cs_monero_flutter_libs
    platforms:
      android:
        package: com.cypherstack.cs_monero_flutter_libs_android
        pluginClass: CsMoneroFlutterLibsAndroidPlugin
        dartPluginClass: CsMoneroFlutterLibsAndroid
