name: cs_salvium_flutter_libs_linux
description: Linux implementation of cs_salvium_flutter_libs
version: 1.0.0-pre
repository: https://github.com/cypherstack/cs_monero
homepage: https://github.com/cypherstack/cs_monero
issue_tracker: https://github.com/cypherstack/cs_monero/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_salvium_flutter_libs_platform_interface: 1.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  plugin_platform_interface: ^2.0.2

flutter:
  plugin:
    implements: cs_salvium_flutter_libs
    platforms:
      linux:
        pluginClass: CsMoneroFlutterLibsLinuxPlugin
        dartPluginClass: CsMoneroFlutterLibsLinux
