name: cs_monero
description: A monero (and wownero) library
version: 0.0.1-dev.0
repository: https://github.com/cypherstack/cs_monero
homepage: https://github.com/cypherstack/cs_monero
issue_tracker: https://github.com/cypherstack/cs_monero/issues

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.0
  logger: ^2.4.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^14.0.0
