name: cs_salvium
description: A cs_salvium library
version: 1.0.0-pre.3
repository: https://github.com/cypherstack/cs_salvium
homepage: https://github.com/cypherstack/cs_salvium
issue_tracker: https://github.com/cypherstack/cs_salvium/issues

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  ffi: ^2.1.0
  logger: ^2.4.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  ffigen: ^14.0.0
