name: cs_salvium_flutter_libs_windows
description: Windows implementation of cs_salvium_flutter_libs
version: 1.0.0
repository: https://github.com/cypherstack/cs_salvium
homepage: https://github.com/cypherstack/cs_salvium
issue_tracker: https://github.com/cypherstack/cs_salvium/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_salvium_flutter_libs_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: CsSalviumFlutterLibsWindowsPluginCApi
        dartPluginClass: CsSalviumFlutterLibsWindows
